### ISSUE TITLE
TB Management - Case Management [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1021]
## Issue
In a TB Management encounter, the CHW has the option for follow-up in one day or one week. Either option should create a follow-up in a new "TB Management" section of the Case Management screen.

Logic for display on the case management "pills" should follow AI case management, that is 
- This week: follow-up due within 7 days
- This month: follow-up due in 7 days or more
- Due today: follow-up due today.
- Past due: followup was due in the past

<img width="612" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/d1977cf9-d5b9-4aac-b829-b7f76de0921a">
<img width="659" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/e08d81fa-1ffa-43b9-bd98-98f30279840c">

Resolution of a case management follow-up should occur if the patient has a TB Management encounter when that follow-up is active (whether or not they entered through the case management screen). That is, any case management encounter should clear previous follow-ups, and a patient can only have one TB Management follow-up at a time.

## Tasks
- Create the follow-up infrastructure
- Create the logic for the creation of a follow-up and its resolution
- Render the page for TB Management on the Case Management screen

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions:

1. When I create a follow up for 1 week, I don't see it under case management at all.

### Checked and approved:

1. Case managements for TB display correctly except 'This month'

Past due|Today|This week
-|-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/baa4eb03-dcdf-4abd-87c3-21ea4ce06345)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/3c26811f-78fa-4cad-b8d9-deceadaded7d)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/8d0d4d7e-05f5-483d-abed-790b24c6e0ca)

**Comment by adamhstewart** [comment]
@anvmn I believe the issue identified avbove was fixed in another issue - can you verify?

**Comment by anvmn** [comment]
@adamhstewart
Well, no, it wasn't fixed, but I believe this is by design.
The thing is that follow up is scheduled today, and since we don't allow multiple encounters on the same day, we don't show the entry on case management.

**Comment by adamhstewart** [comment]
@anvmn Thanks - that makes sense.

**Comment by adamhstewart** [comment]
@anvmn Can you recheck this? https://github.com/TIP-Global-Health/eheza-app/issues/1021#issuecomment-2000110333

I've gotten reports that even after a day the followup doesn't appear

**Comment by anvmn** [comment]
Fixed and deployed to live
