### ISSUE TITLE
Mild to Moderate Preeclampsia

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1158]
Nutrition env

patient Akuzwe Ange

EGA >=20 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) + >= +1 urine protein - in lab

1. Why does Lab activity appear in Case Management for a nurse? After the test is performed by a Lab Technician, it disappears.

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f0fdf325-fc04-4809-9dcd-a2b1131d8dc0">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/aa61f106-579f-4885-8c59-af914fc14944">|
---|---

2. When selecting a long dip, two results appear for a Lab Technician (for short and long dips). 

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8eb8bd6a-89e2-4a99-8fa4-8c66a7d81f3d">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c70dbeea-62e5-448c-aa5a-77ce5b2f4e9f">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b1721e1b-6b5f-424d-ae71-7f8612e6ba22">
---|---|---

3. After submitting the result, the entry with the patient still appears (for short and long dips). 

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cddaacdc-09ae-466f-ad6c-9b2537b44c58">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/73fcdc6b-f28c-4a76-a23b-813533cdee97">
---|---

short dip - patient Akuzwe Annet

<img width="352" alt="Screenshots_-_Google_Drive" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/099f2120-b641-48d7-bf9a-74e020281b32">|<img width="352" alt="Screenshots_-_Google_Drive" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1a808f40-1f4b-4df7-aad2-b932c4c434ff">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> Why does Lab activity appear in Case Management for a nurse? After the test is performed by a Lab Technician, it disappears

Even though labs were ordered, Nurse can fill the results. Therefore sees the activity and can fill the results.
If lab tech filled the results, nurse should not see the activity.
This behaviour is as expected.

> points 2 + 3 

Corrected at #1164

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Questions/Found Issues:
1. Patient Akuzwe Raissa. After submitting the result, the entry with the patient still appears (for short and long dips). If there are other tests, the entry disappears.


<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a36a048d-c089-49bb-8a57-e06c672533de">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/aa1df06d-c370-4aa7-8ef2-9af0c3e7835d">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e35c4dd3-0dd3-4e6d-9455-7aa6c67d9083">
---|---|---

2. Patient Akuzwe Raissa.  Why is the “Leave encounter” button enabled? If there are other diagnoses, the disabled "End encounter" button is shown. (for short and long dips).

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/17994806-df7f-4b0c-b029-c98261d91535">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cb7605bb-c37b-444a-a53b-c62a4b21c067">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5e3e37bb-3e4b-4f7d-819d-7a9faa814521">
---|---|---

### Checked and Approved:
1. When selecting a long dip, one results appears for a Lab Technician

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/47761a54-0f8c-4eeb-a64b-076644cd23d8">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2edf88b8-565c-4fb4-8cdb-681949d6447f">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/525aaa40-2038-429d-808a-6a5480f38f30">
---|---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1.Patient Akuzwe Raissa. After submitting the result, the entry with the patient still appears (for short and long dips). If there are other tests, the entry disappears.

Fixed at #1170.

> 2.Patient Akuzwe Raissa. Why is the “Leave encounter” button enabled? If there are other diagnoses, the disabled "End encounter" button is shown. (for short and long dips).

Label logic: 
- If nurse has completed all activities => end enclunter
- Otherwise (lab tech, or nurse with pending activities) => leave encounter.

**Comment by anvmn** [comment]
@LudmilaGoichman

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Checked and Approved:
1. After submitting the result, the entry with the patient disappears.

EGA >=20 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) + >= +1 urine protein (labs - urine dipstick) | EGA >=20 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) +  >= +1 urine protein (labs - urine dipstick) 
---|---
<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bb22e52f-54eb-4ec2-86b3-36f47473cfd8">|<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4e521ab0-8f37-42e9-b283-58be3988f7bc">
<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9f706326-bdb8-40c7-b764-645aba955bb4">|<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e52210ab-ceb7-4324-a997-af6e5d8c11ae">

**Comment by anvmn** [comment]
Deployed to live
